### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by Linuus** [tarsius/minions#10]
Hi!

I just updated to version `minions-20180306.5` from `minions-20180227.1031` and now it does not work anymore. By not working I mean it just shows all the minor modes directly in the mode line :)

My setup:
```
(use-package minions
  :init
  (setq minions-mode-line-lighter "⚇")
  (setq minions-direct '(flycheck-mode))
  :config
  (minions-mode 1))
```

Should I do something differently in my setup now?

**Comment by tarsius** [comment]
Do you get a `Cannot turn on Minions mode` error?

**Comment by Linuus** [comment]
Nope.

**Comment by Linuus** [comment]
Thanks for the fix!
