### ISSUE TITLE
Minions mode doesn't change current buffers mode-line

### ISSUE THREAD

**Issue by casouri** [tarsius/minions#12]
You used `setq-default` in minor mode definition. That doesn't change current buffer's mode-line-format. Is there any reason for that?

https://github.com/tarsius/minions/blob/acac7fb0b04ffdf243775231690956d163474177/minions.el#L112

When I try to autoload minions like this:

```lisp
(use-package minions
:defer 2
:config (minions-mode 1))
```

Mode-line doesn't change if I have opened a buffer before autoload take place.

**Comment by tarsius** [comment]
Minions has no mechanism for changing the `mode-line-format` for existing buffers, so it has to be loaded at startup (before the creation of the first buffer), which you can do by removing `:defer 2`.

**Comment by casouri** [comment]
👌
