### ISSUE TITLE
Throwing error on reload

### ISSUE THREAD

**Issue by ambihelical** [tarsius/minions#13]
It seems that if minions-mode doesn't detect that it's substitution of the mode-line-format resulted in any changes, it throws an error.  I see this generally during config dev when manually reloading part of my config which causes minion-mode to run via hook.   Since it's already run once, the mode-line-format already has the necessary changes. 

I'm not sure yet why this bit of code is actually used, what does it matter if the mode-line-format already has the substitutions you expect to make?   Could it just be a message instead?

**Comment by jtecca** [comment]
I can confirm that I'm having the same issue on `GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30`.  Looking at the autoloads file, I don't see any obvious issues, but it doesn't look like the minions-mode variable is changing to a non-nil value after minions-mode the function is enabled, which might be causing this behavior.

**Comment by jtecca** [comment]
Looks like it's the following if statement that is causing the issue:

```
        (if (eq banana (default-value 'mode-line-format))
            (progn (setq minions-mode nil)
                   (error "Cannot turn on Minions mode"))
          (setq-default mode-line-format banana)))```

Because if you reload, banana is the same as the default value of mode-line-format.  I'm not sure what the intention of setting minions-mode to nil and throwing the error, but perhaps there should be a check to see if minions-mode is already set before throwing the error.  @tarsius maybe you can explain what the logic here?

**Comment by jtecca** [comment]
https://github.com/tarsius/minions/pull/15 should hopefully address this, pending @tarsius's approval.

**Comment by tarsius** [comment]
The idea is that when turning on `minions-mode` fails to do its thing, then the user should be informed about that. The problem is that we cannot distinguish between the mode being in the process of being turned on for the first time and the mode being turned on while already being on.

**Comment by tarsius** [comment]
I've remove the sanity check for now.
