### ISSUE TITLE
Compatible with doom-modeline

### ISSUE THREAD

**Issue by seagle0128** [tarsius/minions#19]
Hi, `minions` is compatible with `doom-modeline` now. Please refer to https://github.com/seagle0128/doom-modeline/issues/70.

![minions](https://user-images.githubusercontent.com/140797/50301291-de857c00-04c1-11e9-84c5-bfbc8de8295f.png)

Config:
```elisp
(setq doom-modeline-minor-modes t)
(minions-mode 1)
```

I think https://github.com/tarsius/minions/wiki should be updated.

**Comment by tarsius** [comment]
Thanks! I've updated the wiki.
