### ISSUE TITLE
Current Python virtualenv display

### ISSUE THREAD

**Issue by thepreacher** [tarsius/minions#20]
Hi is there anyway to have minions display the current active python virtualenv? Just that I prefer to be aware what python environment I'm working in at a glance and the same for projectile projects. Thanks.

**Comment by tarsius** [comment]
I don't know. What package inserts that into the mode-line? Does it put the information where the minor-mode indicators go (when not using minions)? Have you tried add "the appropriate minor-mode" to `minions-direct`?
