### ISSUE TITLE
display multiple cursors count?

### ISSUE THREAD

**Issue by andreyorst** [tarsius/minions#21]
It seems that minions can temporarily display minor modes in Magit:

![image](https://user-images.githubusercontent.com/19470159/56470571-6cfa1200-6450-11e9-9c08-e4950e82de2d.png)

I wonder if I can achieve the same thing for multiple cursors. Without `minions-mode` when there are several cursors active the modeline displays count:

![image](https://user-images.githubusercontent.com/19470159/56470585-a16dce00-6450-11e9-96a4-4a6d6a7ad4f5.png)

But with `minions-mode` turned on I loose this useful metric completely. It helps me see when there are cursors offscreen and when cursors overlapping.

**Comment by tarsius** [comment]
Use option `minions-whitelist` for that.

**Comment by andreyorst** [comment]
But it doesn't work.

I've added `(add-to-list 'minions-whitelist '(multiple-cursors-mode))` to my configuration, and current value of this list is:
```
((multiple-cursors-mode) (abbrev-mode) (auto-fill-mode) (auto-revert-mode) (auto-revert-tail-mode) (flyspell-mode) (font-lock-mode) (glasses-mode) (hide-ifdef-mode) (highlight-changes-mode) (outline-minor-mode) (overwrite-mode) (ruler-mode))
```

However nothing is displayed. I also don't see `auto-fill` and `auto-revert` modes when working with Org, but they are definitively on.

**Comment by tarsius** [comment]
Ah sorry, confused `minions-whitelist` with `minions-direct`. (Also see the other options in the `minions` Custom group.)

**Comment by andreyorst** [comment]
Ah, got it. I though that `direct` will always show me multiple cursors even if there's none at the moment. Thanks
