### ISSUE TITLE
Incompatibility with ERC tracking mode

### ISSUE THREAD

**Issue by cyrus-and** [tarsius/minions#22]
ERC (IRC client for Emacs) provides a minor mode (`erc-track-minor-mode`) that displays an indicator on the modeline when there is some activity in one of its hidden buffers, for example (note the `[#]`):

    -UUU:@----F2  *scratch*      All (1,0)       [#] (Fundamental Z W) ----------

With minions said indicator disappears:

    -UUU:@----F2  *scratch*      All (1,0)      (Fundamental ···) ----------

Is this a bug or is there anything I can do to make it coexist with minions?

**Comment by tarsius** [comment]
You'll have to redefine `erc-track-add-to-mode-line`, replacing every occurrence of `mode-line-modes` with `minions-mode-line-modes`.

**Comment by tarsius** [comment]
You can also turn on `erc-tracking-minor-mode` before modifying the mode-line. The drawback of this approach is that you have to load `erc` at startup.

**Comment by cyrus-and** [comment]
Thanks for your reply.

> You can also turn on `erc-tracking-minor-mode` before modifying the mode-line.

If I turn on `minions-mode` after ERC the problem still arises and toggling it causes the switch between the two above examples.

---

I managed to solve this by setting `erc-track-position-in-mode-line` to `t`, in this way the ERC indicator is set at the end of `global-mode-string` thus it does not rely on the value of the `mode-line-modes` variable.
