### ISSUE TITLE
How do I display git branch in modeline?

### ISSUE THREAD

**Issue by thepreacher** [tarsius/minions#24]
First of thanks for all your efforts in making this package. I've tried everything I know to display the git branch in the modeline but have failed so far. Below is my current setting for both `Minions` and `Moody` hoping you can spot something that I've missed.

```
;; A minor-mode menu for the mode line
(use-package minions
  :ensure t
  :config
  (setq
    minions-mode-line-lighter "[+]"
    minions-direct '(flycheck-mode pyvenv-mode))
  (minions-mode 1))

;; Tabs and ribbons for the mode line
(use-package moody
  :ensure t
  :config
  (setq x-underline-at-descent-line t
        moody-mode-line-height 25
        moody-slant-function #'moody-slant-apple-rgb)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode))
```

**Comment by tarsius** [comment]
`moody` merely changes how this information looks and `minions` has nothing to do with it at all.

`vc` is the package that displays that information. Start by disabling `minions` and `moody` (and other mode-line packages if any). Restart Emacs. Is the information visible now? If not, then look at variables such as `vc-handled-backends`.

**Comment by thepreacher** [comment]
Thanks for the pointer @tarsius I (or rather a code I copied) was setting the vc-handled-backends to nil. All fixed now. Cheers.
