### ISSUE TITLE
Click off Menu: dings

### ISSUE THREAD

**Issue by jdtsmith** [tarsius/minions#25]
If you summon the minions menu just to check which minor modes are on, and then click off of the menu to exit, it reports `Quit` and dings.

**Comment by tarsius** [comment]
I do not know how one goes about to prevent that. Could you please investigate and come up with a solution? I am a bit busy right now.

**Comment by jdtsmith** [comment]
OK took a look.  `popup-menu` calls the internal `x-popup-menu` function, which explicitly says:

> If the user gets rid of the menu without making a valid choice, for
instance by clicking the mouse away from a valid choice or by typing
keyboard input, then this normally results in a quit and
‘x-popup-menu’ does not return.  But if POSITION is a mouse button
event (indicating that the user invoked the menu with the mouse) then
no quit occurs and ‘x-popup-menu’ returns nil.

So I first tried having `minions-minor-mode-menu` take a mouse event and pass it along as the position, but the problem is `popup-menu` "normalizes" all incoming positions using `popup-menu-normalize-position`, stripping the event designation.  Normalizing mouse events seems like a bug in `popup-menu` to me, since `x-popup-menu` explicitly takes mouse events and behaves differently with them.  I.e. there is no way to `indicat[e] that the user invoked the menu with the mouse`.

I did find one workaround: if you pretend this menu is from a menu-bar item, it formats a position with a `nil` menu that encourages `x-popup-menu` not to quit if no valid click happens (at the end of `minions-minor-mode-menu`):

```elisp
    (popup-menu map nil nil t)))
```

No idea how robust a fix this is, but it does the job.

**Comment by tarsius** [comment]
Thanks!

> Normalizing mouse events seems like a bug

It seems weird indeed. Please ask for some insights on emacs-devel.

**Comment by jdtsmith** [comment]
Asked for insight and didn't converge on a simple answer/solution.  Eli asked why don't just use x-popup-menu with a mouse event.  Any reason that wouldn't work?

**Comment by tarsius** [comment]
I suppose I figured that `x-` stands for `X11` and that that is still relevant.  Now I assume it's not.  ;-)

**Comment by Eli-Zaretskii** [comment]
Nowadays `x-popup-menu` works on all supported terminals, including on TTY frames.

**Comment by tarsius** [comment]
Thanks for the research and help.
