### ISSUE TITLE
How do I exclude a minor mode from being hidden?

### ISSUE THREAD

**Issue by ianpan870102** [tarsius/minions#26]
I'm not sure if it's mentioned somewhere, but I couldn't find it. I'd love to hide 99% of my minor modes with minion, but keep modes like "projectile" or "lsp" visible. This is my attempt so far:

```emacs-lisp
(use-package minions
  :config
  (minions-mode +1)
  (add-to-list 'minions-whitelist '(projectile-mode))
  (add-to-list 'minions-whitelist '(lsp-mode)))
```

**Comment by tarsius** [comment]
`minions-whitelist` is about always displaying certain modes in the *menu*.

Keeping certain (enabled) modes directly in the mode-line instead of listing them only in the menu is not supported.
