### ISSUE TITLE
The *Messages* buffer isn't minionized :-)

### ISSUE THREAD

**Issue by peterwu** [tarsius/minions#28]
The **\*Messages\*** buffer doesn't seem to be affected. Please see the screenshots below. Thanks.
![minions-good](https://user-images.githubusercontent.com/584751/103424866-c3ec4000-4b7c-11eb-9f01-8915c249e2e3.png)
![minions-bad](https://user-images.githubusercontent.com/584751/103424867-c51d6d00-4b7c-11eb-99cc-90ce7d362d68.png)

**Comment by tarsius** [comment]
For me it is. Maybe the mode-line of that buffer was last redisplayed before the mode was turned on? Do `(redisplay t)` or do something that triggers a redisplay such as resizing the frame.

**Comment by peterwu** [comment]
I narrowed down the problem and it turned out to be some evil plugins. Certain packages, such as evil-commentary, evil-exchange have to be labeled as `:after evil` to make minions happy. Some, such as evil-args, don't need the label.

I'm still looking into why but I'll go ahead and close this issue. Thanks very much and happy new year!

**Comment by peterwu** [comment]
I can reproduce the problem with the following minimal setup. It is evil mode that disturbs the minions.

As soon as I disable evil, the problem goes away. 


```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(setq custom-file "~/.config/emacs/custom.el")

(use-package evil
             :ensure t
             :config
             (evil-mode +1))

(use-package minions
  :ensure t
  :config (minions-mode +1))

(use-package which-key
  :ensure t
  :config (which-key-mode +1))
```
