### ISSUE TITLE
Some unicode symbols significantly increase startup time

### ISSUE THREAD

**Issue by JesusTorrado** [tarsius/minions#40]
Hi @tarsius 

First of all, thanks for this fantastic package!

I was trying to set up the menu symbol in the modeline as a hamburguer-like unicode character with three bars, which is mentioned somewhere else (https://www.fileformat.info/info/unicode/char/2630/index.htm). This happens to add approximately 2 seconds to my startup time, which seems bizarre. Interestingly, ESUP (https://github.com/jschaf/esup) doesn't pick this delay up. Other more common unicode symbols (e.g. emojis) do not have that effect.

For reference, I am using a self-compiled emacs 29.1 with Roboto Mono.

Probably not a bug, or nothing can be done about it (e.g. the font does not contain the glyph and it needs to be looked-up at startup). In that case, please feel free to close.

**Comment by tarsius** [comment]
> Probably not a bug, or nothing can be done about it (e.g. the font does not contain the glyph and it needs to be looked-up at startup). In that case, please feel free to close.

I would guess something along those lines and indeed that is something I cannot do anything about.

**Comment by JesusTorrado** [comment]
No worries, and thanks again!

At least I hope this will show up in search results, in case someone has the same problem as me.
