### ISSUE TITLE
Cannot control face (and presence) of major mode name

### ISSUE THREAD

**Issue by JesusTorrado** [tarsius/minions#41]
Hi @tarsius,

Thanks for the great package!

I am failing to change the face of the major mode name (`mode-name`) inserted inside the `minions-mode-line-modes` object. A `propertize` affecting `minions-mode-line-modes` does not do the job, since `mode-line` is already under a `propertize`, and they cannot be nested. So I end up with something similar to what was found in https://github.com/tarsius/minions/pull/32, but without using any mode-line modification package.

Would if be possible to add and expose a custom face for the major mode name, or, alternatively, an option to remove it from the `minions-mode-line-modes` so that its face can be changed separately? I may be able to write a PR for the 2nd case, though my elisp is not very good at all and it would need some review.

**Comment by JesusTorrado** [comment]
Thanks for the quick answer!

> Please post the code you have come up with so far.

https://github.com/tarsius/minions/compare/main...JesusTorrado:minions:major_mode_switch

The 2nd blob takes care of the optional space between major mode name and the minor modes lighter,

> > Would if be possible to add and expose a custom face for the major mode name
> 
> That might be an option, but it might be best that would be done in Emacs. `minions-mode-line-modes` is a copy of `mode-line-modes`, which adds the delimiters and menu; but the major-mode part is the same in both formats (except we had some newlines to the help-text).

It could, sure. But unless I am missing something (again, not an elisp expert) one would need to redefine all the properties, including the help-text in the new definition, just to change the face?

**Comment by tarsius** [comment]
Try this instead:

```elisp
(push 'warning (cddr (caddr minions-mode-line-modes)))
(push 'face (cddr (caddr minions-mode-line-modes)))
```

**Comment by JesusTorrado** [comment]
Sorry, you got me there. Where should I try this?

**Comment by tarsius** [comment]
Add it to your init file, right after `(require 'minions)`.

**Comment by JesusTorrado** [comment]
I see, sorry. Thanks!

It does the job for the major mode name, but it does not apply to the extra text added by some modes, as shown below for the `/l` for lisp lexical binding:

```elisp
(defface mm
  '((default nil)
    (((class color)) :foreground "Blue" :background "DarkOrange2")
    )
  "desc")

(require 'minions)
(push 'mm (cddr (caddr minions-mode-line-modes)))
(push 'face (cddr (caddr minions-mode-line-modes)))
```

![image](https://github.com/tarsius/minions/assets/2233649/9ca0697b-1a12-4396-aa1b-f122fe591667)

**Comment by tarsius** [comment]
> it does not apply to the extra text added by some modes

IMO that's acceptable. In the case of Elisp, the `/d` is supposed to stand out, to draw attention to the fact that it's not `/l`.

But if you really must, you can do that without modifying `minions.el`:

```elisp
(setcar (cddr minions-mode-line-modes) (your-modified-element)
```

You probably have to use `'(:eval (propertize ...))` instead of `'(:propertize ...)` to override existing faces.

**Comment by JesusTorrado** [comment]
Thanks!

At the end of the day, passing `nil` as `your-modified-element` in your suggestion basically does the same as the change I was proposing (minus conditionally removing the space between major and minor, which can also be achieved without modification).

I guess this is a non-issue, if you prefer to leave minions as-is. I have learned quite a bit from this conversation. Thanks a lot for your time!

**Comment by tarsius** [comment]
You're welcome!
