### ISSUE TITLE
Doesn't work with powerline?

### ISSUE THREAD

**Issue by andreas-h** [tarsius/minions#5]
I have powerline installed, and when I do `(minions-mode 1)`, I get an error "Cannot turn on minions mode".  Is this to be expected?

btw, I think the theme / modeline in the screenshot is very beautiful.  Would you mind sharing which theme you're using and how you're setting up the modeline to look that fabulous? Cheers!

**Comment by tarsius** [comment]
> "Cannot turn on minions mode". Is this to be expected?

Yes, but it can be fixed. What is powerline's equivalent of `mode-line-modes`?

> Would you mind sharing which theme you're using and how you're setting up the modeline to look that fabulous?

That's [`moody`](https://github.com/tarsius/moody).

**Comment by andreas-h** [comment]
Thanks for the info! Unfortunately, I don't have any ideas about powerline's internals, so cannot be of much help here.  And thanks for the pointer to moody - looks very good to me, and I think I'll be using that.

**Comment by tarsius** [comment]
I think `(powerline-minor-modes face1 'l)` is the element that would have to be replaced, but doing that would remove all the `powerline` visuals (if it works at all).

**Comment by tarsius** [comment]
Please see https://github.com/tarsius/minions/wiki.
