### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by DamienCassou** [tarsius/minions#8]
Thank you very much. I've just [removed 51 lines](https://github.com/DamienCassou/emacs.d/commit/5fd1d23877e73a96d794735a2d82880e8c3e723c#diff-64ed6d0a7a4f2eaf33cacc2454a19cff) of my init.el file :-).

**Comment by manuel-uberti** [comment]
^ Did the same thanks to `minions`. :)

**Comment by tarsius** [comment]
You are welcome ;-)
